language: generic
sudo: required

services:
  - docker

git:
  depth: 3

before_install:
  - docker pull fedora

script:
  - >
    docker run -t -v ${PWD}:/testproject fedora /bin/sh -c
    'dnf install -y git python3-numpy;
    python3.5 -mpip install --upgrade pip tox coveralls;
    cd testproject;
    tox -epy35;
    coveralls;'

# Build Triggers
# echo "# `date`" >> .travis.yml
# Wed Mar 22 20:10:59 PDT 2017
