language: python
sudo: required

services:
  - docker

git:
  depth: 3

before_install:
  - docker pull fedora
  - docker ps -a

install:
  - dnf install git python3-numpy
  - python3.5 -mpip install --upgrade pip tox coveralls

script:
  - tox -epy35
  - coveralls

# Build Triggers
# echo "# `date`" >> .travis.yml
# Wed Mar 22 20:10:59 PDT 2017
