language: python
sudo: required

python:
  - "3.6"

services:
  - docker

git:
  depth: 3

install:
  - docker pull fedora
  - pip install --upgrade coveralls

script:
  - >
    docker run -t -v ${PWD}:/testproject fedora /bin/sh -c
    'dnf install -y git python3-numpy;
    python3.5 -mpip install --upgrade pip tox coveralls;
    cd testproject;
    tox -epy35;'

after_script:
    - coveralls

# Build Triggers
# echo "# `date`" >> .travis.yml
# Wed Mar 22 20:10:59 PDT 2017
