language: python
sudo: required

python:
  - "3.5"

services:
  - docker

git:
  depth: 3

install:
  - docker pull fedora
  - pip -q install -U coveralls

script:
  - >
    docker run -t -v ${PWD}:${PWD}:Z fedora /bin/sh -c
    "dnf install -qy git python3-{numpy,tox};
    cd ${PWD};
    tox -epy35;"

after_script:
    - coveralls

# Build Triggers
# echo "# `date`" >> .travis.yml
# Wed Mar 22 20:10:59 PDT 2017
