language: python
sudo: required

services:
  - docker

git:
  depth: 3

before_install:
  - docker pull fedora
  - docker run -it fedora /bin/bash

install:
  - dnf install -y git python3-numpy
  - python3.5 -mpip install --upgrade pip tox coveralls
  - git clone --depth=3 --branch=master https://github.com/theodoregoetz/testproject.git
  - cd testproject

script:
  - tox -epy35
  - coveralls

# Build Triggers
# echo "# `date`" >> .travis.yml
# Wed Mar 22 20:10:59 PDT 2017
